### ISSUE TITLE
Ko-Fi Problem

### ISSUE THREAD

**Issue by orychalk** [bouteillerAlan/blurredwallpaper#1]
Hello,
I promised on the original Git plugin to send a tips (10€ ) to the one who solve the problem.
And you did what I'm waiting for.
THANK YOU 😃
So I try to send you the tips on Ko-Fi but my payment is not accepted 
Do you have a Patreon ?

**Comment by bouteillerAlan** [comment]
Hello :) thank you very much.
My patreon is still being verified by the patreon staff to validate my account creation.
I have an account on "buy me a coffee" : [https://www.buymeacoffee.com/a2n.dev](https://www.buymeacoffee.com/a2n.dev)

What is the problem with ko-fi, that I ask them if ever I have configured something wrong ^^ ?

**Comment by orychalk** [comment]
Hi,
With coffeeme it's worked 😃
Could you confirm me you received the tip ?

On ko-fi I tried two time and finaly I saw a "Whoops message, something is going wrong", but without explanation...

Can I ask you a service ? (I know it's probably not the right place for this, but I tried ... sorry)
I used for long time another KDE plasma Plugin, and on the last KDE updates (5.26, and 5.27.x) It's didn't work anymore :
https://github.com/zzag/kwin-effects-yet-another-magic-lamp
If you have some time to check what happened and repair/fork it will be great 😃
And I can send you another tip for this work 😄 (And I think I'm not the only one)
Thanks in advance.

**Comment by luisbocanegra** [comment]
> The blur window area stay when we minimize the window. It's a graphic bug. Some people creates some issues, but for the moment , we have no answer/correction. If you have some time to check what happened and repair/fork it will be great smiley And I can send you another tip for this work smile (And I think I'm not the only one) Thanks in advance.

The problem you mention is related to KWin and the way it handles blur regions, specifically, it can only create rectangular blur regions, resulting in the bug you see when performing window deformation effects, you can read more about it here https://bugs.kde.org/show_bug.cgi?id=391819 there is an open KWin merge request that would potentially allow that to be fixed if accepted here https://invent.kde.org/plasma/kwin/-/merge_requests/3407

**Comment by orychalk** [comment]
Hello,
@luisbocanegra : Thanks for the information, I understand 😄
I know the blur region can't be blured when the animation run, but before, the blur was desactivated when the animation launch, now the blur effect stay when the animation start.
The standard Lamp effect provided with Plasma has not this bad behavior in recent Plasma.

**Comment by luisbocanegra** [comment]
> Hello, @luisbocanegra : Thanks for the information, I understand smile I know the blur region can't be blured when the animation run, but before, the blur was desactivated when the animation launch, now the blur effect stay when the animation start. [zzag/kwin-effects-yet-another-magic-lamp#70](https://github.com/zzag/kwin-effects-yet-another-magic-lamp/issues/70) The standard Lamp effect provided with Plasma has not this bad behavior in recent Plasma.

Oh, I see, thought the Plasma one suffered the same issue.

**Comment by bouteillerAlan** [comment]
Hi, I received your tips @orychalk thanks again 🙌

Yes I can look; probably next week; but as said before I'm still new to QML / Plasma, so I don't know how long it can take me. I leave this issue open so I don't forget 😁

**Comment by orychalk** [comment]
@bouteillerAlan 
Thanks 😄

**Comment by bouteillerAlan** [comment]
I have created a task for it : [https://github.com/users/bouteillerAlan/projects/3/views/2?pane=issue&itemId=25728043](https://github.com/users/bouteillerAlan/projects/3/views/2?pane=issue&itemId=25728043)

**Comment by orychalk** [comment]
Hello,

Without putting pressure, were you able to see what the problem was with the plugin kwin-effects-yet-another-magic-lamp ?

Many Thanks 😊
