### ISSUE TITLE
Idea: Support for wallpaper slideshows

### ISSUE THREAD

**Issue by orychalk** [bouteillerAlan/blurredwallpaper#2]
Do you have planned to integrate slideshows ?
It's may be very cool to have multiple wallpapers blurred 😄

Thanks in advance.

**Comment by bouteillerAlan** [comment]
Hi 👋 I have some time next week I can check that :)

**Comment by Shaurya-Kalia** [comment]
> Hi wave I have some time next week I can check that :)

Thanks a lot for considering this. Slideshow blur will encompass the functionality of even the current plugin

**Comment by bouteillerAlan** [comment]
Working on it on https://github.com/bouteillerAlan/blurredwallpaper/tree/feat/slideshow

**Comment by bouteillerAlan** [comment]
Hello there 👋

I don't know how long it takes for the list included in "get a new plugin" to be updated. But I made the feature :smile: 
https://store.kde.org/p/2017888/

There is a problem that is being fixed, when I find out why it exists ^^

**Comment by Shaurya-Kalia** [comment]
Tried it now. Its working perfectly as far as I have tried. Thanks for implementing it. I think its ready for another round at r/kde

**Comment by bouteillerAlan** [comment]
> Tried it now. Its working perfectly as far as I have tried. Thanks for implementing it. I think its ready for another round at r/kde

I have updated the original post, but I don't know if it's a "working" idea, so I planned to make a new one asap :smile: 

Thanks for the test !

**Comment by Shaurya-Kalia** [comment]
I don't think a new plugin is required, since the latest one encompasses the function of earlier too. You can delete the files for older versions from kdestore/pling. That way, existing users will also get an update prompt. Would cause much less confusion if there is single plugin

**Comment by orychalk** [comment]
Great news 😃
Just updated ... It's work perfectly 😊
Thanks 😃👍

**Comment by bouteillerAlan** [comment]
> I don't think a new plugin is required, since the latest one encompasses the function of earlier too. You can delete the files for older versions from kdestore/pling. That way, existing users will also get an update prompt. Would cause much less confusion if there is single plugin

Yes indeed, good call
