### ISSUE TITLE
Laggy when obs-studio is opened

### ISSUE THREAD

**Issue by RosGtHub** [bouteillerAlan/blurredwallpaper#20]
Basically, after opening obs the mouse cursor starts to stutter/lag and all looks laggy.
 
 CPU: AMD Ryzen 5 5600G
 GPU: AMD RX 6700 xt sapphire 12Gb
 RAM: 16 Gb 3600mhz

**Comment by bouteillerAlan** [comment]
Hello, I lost my linux pc, so I don't have the time/stuff yet to test.

But I don't think I can do anything. The blur effect is possibly too greedy and OBS too. 

What tells your system monitor when both of them are launch (ram/cpu/gpu)?

**Comment by RosGtHub** [comment]
Sorry if I'm responding only now. Basically, when I start recording the desktop, the RAM is normal, the CPU is around 30% to 40%, and the GPU experiences occasional spikes between 15% to 25%.

**Comment by bouteillerAlan** [comment]
Hi, I´have found another PC. I have tested the behaviour with obs recording but no lag for me.
In any case, I'm afraid I can do nothing for this kind of problem :/ This type of blur is resource consuming so...

You can check some stats of your recording via the view/stats menu in obs, this window have a "frame lost by rendering lag" line and a "fps" line if you want to check what behaviour seems to cause the lag.

In my case, the more I create visible windows the fewer fps I have and the more "lag" I have: but nothing tremendous (I have pop 10 terminal windows, 10 dolphin window, obs, phpstorm, vivaldi with 10 tabs).
