### ISSUE TITLE
Update for plasma 6 -- not showing up in plasma 6 even after install

### ISSUE THREAD

**Issue by sanotaku09** [bouteillerAlan/blurredwallpaper#23]
### Version

v2.2

### What steps will reproduce the bug?

i installed it 
it showed thats it was installed but when i tapped on drop down menu it wasn't listed there

### How often does it reproduce? Is there a required condition?

it never works in plasma 6
please port it to plasma 6

### What do you see instead?

nothing

**Comment by bouteillerAlan** [comment]
Hi, I've already started modifying the code, but I'm pretty busy and it's taking a long time. FYI I'd like to start pushing code before the beginning of the year if I can.

**Comment by bouteillerAlan** [comment]
Hi @sanotaku09 we have made a release for KDE 6 : [https://www.pling.com/p/2134907/](https://www.pling.com/p/2134907/)
