### ISSUE TITLE
Active blur shows black image in Plasma 6

### ISSUE THREAD

**Issue by archisman-panigrahi** [bouteillerAlan/blurredwallpaper#30]
### Version

3.0.0

### What steps will reproduce the bug?

KDE Plasma 6.0.1 in EndeavourOS. Installed plasma6-wallpapers-blurredwallpaper from the AUR, and enabled Active Blur in wallpaper settings.

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

It should show me the available wallpapers.

### What do you see instead?

It shows a black screen, and there is no option to choose the wallpaper.
![image](https://github.com/bouteillerAlan/blurredwallpaper/assets/3063132/86cf0fca-b1f3-41b1-9861-48e12bd44c49)

**Comment by bouteillerAlan** [comment]
Hey, `plasma6-wallpapers-blurredwallpaper` is not maintain by me. You should use the `plasma-wallpapers-blurredwallpaper-git` package that is up-to-date and working :)
