### ISSUE TITLE
Slideshow wallpaper is broken

### ISSUE THREAD

**Issue by gleyconJ** [bouteillerAlan/blurredwallpaper#31]
### Version

a2n.blur.3.0.0.tar.gz	3.0.0	KDE 6 release	2120	2024-03-04	0.01 MB

### What steps will reproduce the bug?

The slideshow feature does not work, the plasma feature does not activate.

### How often does it reproduce? Is there a required condition?

Everytime. It is impossible to activate.

### What is the expected behavior?

I don't know how to do this, I'm a user and not a programmer.

### What do you see instead?

I don't know how to do this, I'm a user and not a programmer.

### Additional information

Nothing.

**Comment by bouteillerAlan** [comment]
Hello :wave: can you tell me which version of plasma you're using please ? 
I specifically need the compositor (x or wayland), you can retrieve that under the system settings : 
![image](https://github.com/bouteillerAlan/blurredwallpaper/assets/30547569/36e3572c-ba77-4e4b-beb1-a0ce04583a18)

Thanks :)

**Comment by bouteillerAlan** [comment]
Could you share, too, a screenshot of your screen for the slideshow please ? Because it's work on my laptop : 
![image](https://github.com/bouteillerAlan/blurredwallpaper/assets/30547569/f51fe176-951b-4f72-ac1f-f0444654cd7a)

The bug that we have atm for the switch between img and slideshow is that you have to hit "apply", "ok" then re-open the wallpaper settings (I'm working on it) :
*sorry for the frame rate 😅*
[Kooha-2024-03-28-09-55-52.webm](https://github.com/bouteillerAlan/blurredwallpaper/assets/30547569/044a948b-f5c7-4aba-a946-30cc066d8315)

Related bug : #32 #33

**Comment by gleyconJ** [comment]
![imagem - 2024-03-28 -- 12 34](https://github.com/bouteillerAlan/blurredwallpaper/assets/90162684/363da753-65f7-4809-bd5a-355b61c7f530)

**Comment by gleyconJ** [comment]
![imagem - 2024-03-28 -- 12 39](https://github.com/bouteillerAlan/blurredwallpaper/assets/90162684/5407c51a-3aad-4edf-8c86-930cd0cdb4a6)

**Comment by gleyconJ** [comment]
![Uploading imagem - 2024-03-28 -- 12 40.png…]()

**Comment by gleyconJ** [comment]
![imagem - 2024-03-28 -- 12 40](https://github.com/bouteillerAlan/blurredwallpaper/assets/90162684/f6abe962-abd9-4560-9e9c-57dfcb564f84)

**Comment by gleyconJ** [comment]
The issue here is that the native slideshow add-on is working normally. That's why I posted an image. Now your plasmoid realizes that it doesn't recognize my images and if I try to add a folder of images it breaks and restarts the plasma.

**Comment by bouteillerAlan** [comment]
Hello sorry for the late reply I have some health issue atm.

I know this bug and I don't know how to fix it, I tried many think but nothing work :/ 

The only workaround I found atm is described in the message just before the checkbox : 
![image](https://github.com/bouteillerAlan/blurredwallpaper/assets/30547569/cca2f48d-80bf-41a4-a906-d479f409d48f)

**Comment by bouteillerAlan** [comment]
related to #25 #35
