### ISSUE TITLE
plasmashell API

### ISSUE THREAD

**Issue by FroggerHH** [bouteillerAlan/blurredwallpaper#34]
Hello 👋. Does it have an api to switch to next slideshow image?  And if is has, how to use it? Thanks

**Comment by bouteillerAlan** [comment]
Hello, I just duplicated the slideshow coded by KDE so you have to look at their side to get an answer ^^ on my side I did not create an api to interact with

**Comment by FroggerHH** [comment]
> Hello, I just duplicated the slideshow coded by KDE so you have to look at their side to get an answer ^^ on my side I did not create an api to interact with 

Can I please have a link 🙏?

**Comment by bouteillerAlan** [comment]
In general I use this site, but their documentation isn't really up to date :/ it's always a bit tricky to find what you're looking for. 
[https://develop.kde.org/](https://develop.kde.org/)
