### ISSUE TITLE
Crash when removing/adding folders from slideshow

### ISSUE THREAD

**Issue by kodingkatmc** [bouteillerAlan/blurredwallpaper#35]
### Version

latest as of 7/6/24

### What steps will reproduce the bug?

Enable Wallpaper Type: Active Blur
Enable 'Slideshow'
Enable 'Active Blur'
Attempting to remove/add any folders will crash KDE Settings and/or KDE Plasma Desktop
![image](https://github.com/bouteillerAlan/blurredwallpaper/assets/67832156/96952b79-2ffb-40b7-9cfe-d1e6ef945d6d)

### How often does it reproduce? Is there a required condition?

Everytime

### What is the expected behavior?

Doesn't Crash

### What do you see instead?

Crash

### Additional information

**Workaround:**

No crash occurs if 'Active Blur' is unchecked; i.e. follow the above steps but UNCHECK 'Active Blur'.
![image](https://github.com/bouteillerAlan/blurredwallpaper/assets/67832156/c9dccef4-1e84-4606-ae7c-7c5434ad44f1)
'Active Blur' can then be re-enabled after the desired folders are configured.

From this, I conclude that it may be a simple fix, but I could be wrong.

**Comment by bouteillerAlan** [comment]
Hello, the problem is very much the same as describe in the warning modal, when you change between slideshow & not slideshow you have to hit apply then re-open the setting windows. I don't understand why this part won't charge properly. I'm still trying to solve the problem.

**Comment by bouteillerAlan** [comment]
related to #25
