### ISSUE TITLE
Unblur Wallpaper, when Desktop is in Focus after minimizing window.

### ISSUE THREAD

**Issue by kneckergit** [bouteillerAlan/blurredwallpaper#38]
### What is the problem this feature will solve?

The title says it all. When a window gets minimized and the desktop is in focus, the blur should disappear. The older plugin "inactive blur" did exactly that, btw.

### What is the feature you are proposing to solve the problem?

As stated above...

### What alternatives have you considered?

None. I am indoctrinated by this plugin for live. There is no alternative. All hail the active blur!

**Comment by bouteillerAlan** [comment]
link to #25
