### ISSUE TITLE
Cannot get the plugin to work on Kubuntu

### ISSUE THREAD

**Issue by Master449** [bouteillerAlan/blurredwallpaper#4]
### Version

v1

### What steps will reproduce the bug?

I am not sure, I only just installed the plugin.

### What do you see instead?

Nothing changes. There is no blur effect at all, and upon reentering the Settings interface, it has defaulted back to what I had originally.

I cannot seem to select any wallpaper, and cannot apply anything.

[screen.webm](https://user-images.githubusercontent.com/20436145/232619072-d49ab8b6-d009-474b-818e-30d739ed3b90.webm)

### Additional information

I did get this log from journalctl

```
Apr 17 16:31:23 powerhouse plasmashell[1891]: file:///home/david/.local/share/plasma/wallpapers/a2n.blur/contents/ui/config.qml:51: TypeError: Property 'commitAddition' of object BackgroundListModel(0x5639c40e8970) is not a function
```

Running Kubuntu 22.10, Kernel 6.2.0, plasmashell 5.25.5

**Comment by pragit-raj-sharma** [comment]
The same issue is with inactive blur plugin after plasma v5.25 update. 
Doesn't know the exact reason but you should upgrade plasmashell to newer version. That might help.

**Comment by bouteillerAlan** [comment]
Keep me in touch if the update of plasma doesn't work :+1:

**Comment by Master449** [comment]
Works perfect on Plasma 5.27!

Thank you guys,

Closing.
